version: "3.7"

services:
  sftp_prod:
    image: atmoz/sftp:latest
    volumes:
      - ./share:/home/wowwaw/share
    ports:
      - "2222:22"
    command: wowwaw:pass:::share
    restart: always

  sftp_staging:
    image: atmoz/sftp:latest
    volumes:
      - ./share2:/home/wowwaw/share2
    ports:
      - "222:22"
    command: wowwaw:pass:::share2
    restart: always

  database:
    image: mysql:5.7
    container_name: database
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "acrarium"
      MYSQL_USER: "acrarium"
      MYSQL_PASSWORD: "secure_password"
    expose:
      - "3306"
    volumes:
      - acrarium_data:/var/lib/mysql
  acrarium:
    image: f43nd1r/acrarium:1.6.1
    container_name: acrarium
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/acrarium?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "acrarium"
      SPRING_DATASOURCE_PASSWORD: "secure_password"
      SPRING_JPA_DATABASEPLATFORM: org.hibernate.dialect.MySQL57Dialect

volumes:
  acrarium_data:
