name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Release notes
        run: sed "1,/## ${{ env.TAG }}/d;/## v/Q" ./CHANGELOG.md > release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release.txt